M48
; DRILL file {KiCad 7.0.8} date Sat Nov  4 22:50:30 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-11-04T22:50:30-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.8
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0866
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1260
%
G90
G05
T1
X4.3Y-2.925
X4.3Y-3.825
T2
X2.4729Y-5.8499
X3.4479Y-4.0749
X3.85Y-5.85
X4.825Y-4.075
T0
M30
